version: '3'

services:
  back-end:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      ## npm run start
      target: prod
    # npm run dev
    # target: dev
    ## npm run test
    # target: test
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - '5050:80'
    restart: always
